### PR TITLE
Enabled FindBugs plugin again, fixed regex

### PR DESCRIPTION
**Pull request by bearcheese**
Small KAIZEN here, switched back FindBugs on the project.

### CODE REVIEW

**Comment by bearcheese** [comment]
@kelemena could you please build this branch locally and check whether it's working for you?

**Comment by kelemena** [comment]
Sure

**Comment by kelemena** [comment]
Wokring

**Comment by kelemena** [comment]
@bearcheese Findbugs makes our build 4 times slower 20s -> 1.20m. We should run it later in a separate build.

**Pull request merged**
